apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: online-boutique

resources:
- ../../base/online-boutique

patches:
- path: patch-frontend.yaml
- path: patch-cartservice.yaml
- path: patch-productcatalogservice.yaml
- path: patch-currencyservice.yaml
- path: patch-checkoutservice.yaml
- path: patch-shippingservice.yaml
- path: patch-emailservice.yaml
- path: patch-paymentservice.yaml
- path: patch-recommendationservice.yaml
- path: patch-adservice.yaml
- path: patch-redis-cart.yaml
