apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/online-boutique

patches:
- path: node-affinity-patch.yaml
  target:
    kind: Deployment
    namespace: online-boutique
